### ISSUE TITLE
Revise BookFormat field

### ISSUE THREAD

**Issue by PrycilaCerqueira** [PrycilaCerqueira/P7_UrbanRead#13]
The field will be used when the user uploads the purchased book. The area should accept any format and convert to others - PDF, MOBI, etc

**Comment by PrycilaCerqueira** [comment]
"saleInfo": {
        "country": "CA",
        "saleability": "NOT_FOR_SALE",
        **"isEbook": false**
      },
      "accessInfo": {
        "country": "CA",
        "viewability": "NO_PAGES",
        "embeddable": false,
        "publicDomain": false,
        "textToSpeechPermission": "ALLOWED",
        **"epub": {
          "isAvailable": true
        },
        "pdf": {
          "isAvailable": true**
        }



saleInfo": {
        "country": "CA",
        "saleability": "FOR_SALE",
        **"isEbook": true,**
        "listPrice": {
          "amount": 10.99,
          "currencyCode": "CAD"
        },
        "retailPrice": {
          "amount": 10.99,
          "currencyCode": "CAD"
        },
        **"buyLink":** "https://play.google.com/store/books/details?id=gzYQCwAAQBAJ&rdid=book-gzYQCwAAQBAJ&rdot=1&source=gbs_api",
        "offers": [
          {
            "finskyOfferType": 1,
            "listPrice": {
              "amountInMicros": 10990000,
              "currencyCode": "CAD"
            },
            "retailPrice": {
              "amountInMicros": 10990000,
              "currencyCode": "CAD"
            },
            "giftable": true
          }
        ]
      },
      "accessInfo": {
        "country": "CA",
        "viewability": "PARTIAL",
        "embeddable": true,
        "publicDomain": false,
        "textToSpeechPermission": "ALLOWED",
        **"epub": {
          "isAvailable": true,**
          "acsTokenLink": "http://books.google.ca/books/download/Harry_Potter_e_o_C%C3%A1lice_de_Fogo-sample-epub.acsm?id=gzYQCwAAQBAJ&format=epub&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api"
        },
        **"pdf": {
          "isAvailable": true,**
          "acsTokenLink": "http://books.google.ca/books/download/Harry_Potter_e_o_C%C3%A1lice_de_Fogo-sample-pdf.acsm?id=gzYQCwAAQBAJ&format=pdf&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api"
        }

**Comment by f-rakete** [comment]
need more clarification on the problem 🫠

**Comment by PrycilaCerqueira** [comment]
The BookFormat field will be populated by the user when they decide to buy a book and upload to the library
The adjustment required is on the search to allow  users to select: free-ebooks, paid-ebooks, ebooks, all (ebooks or non-ebooks)
