### ISSUE TITLE
Verify duplicate books in library

### ISSUE THREAD

**Issue by PrycilaCerqueira** [PrycilaCerqueira/P7_UrbanRead#18]
Do not add or remove duplicated books in the Library once found.

**Comment by PrycilaCerqueira** [comment]
Hi @f-rakete, the Distinc() seems not to be working on the library.  Error message: https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs1660?f1url=%3FappId%3Droslyn%26k%3Dk(CS1660)

https://github.com/PrycilaCerqueira/P7_UrbanRead/blob/fcbf5a5b164a81377d2e82ad24206339423c8da0/P7_UrbanRead/P7_UrbanRead/Help.cs#L97-L107

**Comment by f-rakete** [comment]
check the docs 🙃 
Distinct doesn't work like you think it does => https://learn.microsoft.com/de-de/dotnet/api/system.linq.enumerable.distinct?view=net-7.0

so the error message also made sense, distinct() takes an equalitycomparer as a parameter, you put a lambda expression in ( num=>num.Isbn)

also not sure why you did the where (maybe out of desperation haha)

so check out the doc i linked, and maybe there is a method thats more promising for what youre trying to do alongside there ;) 

![image](https://github.com/PrycilaCerqueira/P7_UrbanRead/assets/69428398/dcbd3eaa-9cb4-445f-a170-8393aa77678f)

**Comment by PrycilaCerqueira** [comment]
Hi @f-rakete, I've implemented the BookComparer class based on the class and articles 
https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.iequalitycomparer-1?view=net-8.0
https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.distinct?view=net-8.0#system-linq-enumerable-distinct-1(system-collections-generic-ienumerable((-0)))

My code has no syntax nor exception errors, but it is not checking Equals(). I am not sure what I am missing here.
