### ISSUE TITLE
Booktypes / Ebookformat

### ISSUE THREAD

**Issue by f-rakete** [PrycilaCerqueira/P7_UrbanRead#2]
https://github.com/PrycilaCerqueira/P7_UrbanRead/blob/38d970e1da099dbc6dc8da4493944a1c1901311e/P7_UrbanRead/P7_UrbanRead/Book.cs#L22-L23

The book can only be one thing, I'd consolidate the ebook formats into the Booktype enum.

also what would the ebook type be anyways if tis a hardcover book?

**Comment by PrycilaCerqueira** [comment]
I've unified both of them into one (BookFormat.cs)
