### ISSUE TITLE
Unable to Start WebUI.exe "The system cannot find the file specified."

### ISSUE THREAD

**Issue by PrycilaCerqueira** [PrycilaCerqueira/P7_UrbanRead#24]
Error message:

![Image](https://github.com/PrycilaCerqueira/P7_UrbanRead/assets/75625742/591e9f46-ec4f-4023-bfb6-72cf207a1ddb)

**Comment by f-rakete** [comment]
please also include the build logs - this can happen if the build fails or some build settings are wrong

**Comment by PrycilaCerqueira** [comment]
Resolved after adjusted the input of the initiateBookSearch()
