### ISSUE TITLE
Nested nested nested ;)

### ISSUE THREAD

**Issue by mayisa87** [PrycilaCerqueira/P7_UrbanRead#25]
https://github.com/PrycilaCerqueira/P7_UrbanRead/blob/d6bc913b6d0571434113b65164c426c20fe78f4e/P7_UrbanRead/P7_UrbanRead/Help.cs#L116-L161

I wanted to have a look to the current issue of searchBook and ran into a NullPointerException in this method. 

Concerning code structure, always try to avoid too much nested if statements and loops etc. 

So like here:

```
 if (item.Type != null)
{
 .... bla bla
}
else
{
 continue;
}

```
You could make it much easier if you write:
```
 if (item.Type == null")
{
   continue;
}

bla bla
```

And below, you again do the same if, even if you checked before already if item.type is null. 

And I ran into the NullPointerException because, the isbnId is set to null explicitely, so sometimes it happens then, that you access the isbnId object, even if it is null.

Why do you set it to null? If you need it like this, you should always check it before setting properties to it

**Comment by PrycilaCerqueira** [comment]
Hi @mayisa87 and @f-rakete, I believe I managed to improve this method based on the feedback given.
