### ISSUE TITLE
Search by Author's name

### ISSUE THREAD

**Issue by PrycilaCerqueira** [PrycilaCerqueira/P7_UrbanRead#27]
When the author's name triggers the search, no results are shown.

**Comment by f-rakete** [comment]
That Linq statement in https://github.com/PrycilaCerqueira/P7_UrbanRead/commit/f0053f1e4791bd358ceca9b39bad9eee1b5c0d63 seems pretty off to me.

can you clarify what you're trying to do? Just search by author?

**Comment by PrycilaCerqueira** [comment]
Hi @f-rakete, first I need to change all the authors' names to lower case then perform the search for their names through my list

**Comment by f-rakete** [comment]
@PrycilaCerqueira the compare method also takes a second argument on string lists - only a google search away if you search for something like "c# string list contains ignore case"

you're probably looking for something like this:
`list.Contains(text,StringComparer.InvariantCultureIgnoreCase))`

**Comment by PrycilaCerqueira** [comment]
Hi @f-rakete, I've implemented the LINQ query, but it returns an empty list even though I should have data populated
 https://github.com/PrycilaCerqueira/P7_UrbanRead/blob/9911eeb4212c06e78165d5ad835d308dca36ff47/P7_UrbanRead/WebUI/Data/MainDataService.cs#L48

https://github.com/PrycilaCerqueira/P7_UrbanRead/blob/9911eeb4212c06e78165d5ad835d308dca36ff47/P7_UrbanRead/WebUI/Data/MainDataService.cs#L72-74

**Comment by PrycilaCerqueira** [comment]
Resolved
