### ISSUE TITLE
Public repos shouldn't have hardcoded API keys

### ISSUE THREAD

**Issue by f-rakete** [PrycilaCerqueira/P7_UrbanRead#3]
https://github.com/PrycilaCerqueira/P7_UrbanRead/blob/bd65ed044cc0eef1251684e36f8b9064903371cb/P7_UrbanRead/P7_UrbanRead/Program.cs#L19

Best practice is to keep the keys in a local file, that is excluded via the git .ignore file. then the program can load the API key string from that file at runtime

**Comment by PrycilaCerqueira** [comment]
Managed to hide the Secret.cs by using the .gitignore file.
https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files

**Comment by PrycilaCerqueira** [comment]
Resolved. It is finally not showing on GitHub
