### ISSUE TITLE
BookDetails Page

### ISSUE THREAD

**Issue by PrycilaCerqueira** [PrycilaCerqueira/P7_UrbanRead#35]
Create and design a page to present the selected book details to the readers.

![Image](https://github.com/PrycilaCerqueira/P7_UrbanRead/assets/75625742/0acb8c44-f421-480e-9fa9-4099199ec808)

**Comment by f-rakete** [comment]
hey I got tagged here, but i'm not sure what you need 🙃

**Comment by PrycilaCerqueira** [comment]
Hi @f-rakete, I've implemented an iframe to show the book sample to readers. 
There is no error message at this time, but the embedded book doesn't show on the page.
Could you guide me here, please? I guess it is an issue with the page re-render.

**Comment by f-rakete** [comment]
@PrycilaCerqueira you're never calling your GenerateIframeURL method?  🙈So the src tag of the iframe stays empty. If it's set, it works as expected!

quick shorthand way of writing this here as a suggestion  => https://github.com/PrycilaCerqueira/P7_UrbanRead/pull/36

**Comment by PrycilaCerqueira** [comment]
@f-rakete why does it use => instead of = to assign the value to the embeddedURL variable?

**Comment by PrycilaCerqueira** [comment]
The => operator is called the lambda operator in C#. [It is used to define a lambda expression ](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/lambda-operator)[1](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/lambda-operator). In this case, it is used to define a lambda expression that returns a string value. [The lambda expression is then assigned to the embeddedURL variable using the = operator ](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/lambda-operator)[1](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/lambda-operator).

[The => operator separates the input parameters on the left side from the lambda body on the right side ](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/lambda-operator)[1](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/lambda-operator). [The lambda body can be an expression or a statement block ](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/lambda-operator)[1](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/lambda-operator). [In this case, the lambda body is an expression that returns a string value ](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/lambda-operator)[1](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/lambda-operator).

[The use of the => operator in this context is called an expression-bodied member definition ](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/lambda-operator)[1](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/lambda-operator). [It is a shorthand syntax for defining a method or property that has a single expression as its body ](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/lambda-operator)[1](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/lambda-operator). [The => operator is used to separate the member name from the expression body ](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/lambda-operator)[1](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/lambda-operator).

I hope this helps! Let me know if you have any other questions. 😊
