### ISSUE TITLE
One method should have one task only

### ISSUE THREAD

**Issue by f-rakete** [PrycilaCerqueira/P7_UrbanRead#5]
https://github.com/PrycilaCerqueira/P7_UrbanRead/blob/bd65ed044cc0eef1251684e36f8b9064903371cb/P7_UrbanRead/P7_UrbanRead/FuncHelp.cs#L13-L49

this method does 2 things at once, check and add ISBNs. 
Should be split into 2 separate methods (check/add)

**Comment by PrycilaCerqueira** [comment]
Resolved.
