### ISSUE TITLE
This code overwrites the same property multiple times

### ISSUE THREAD

**Issue by f-rakete** [PrycilaCerqueira/P7_UrbanRead#6]
https://github.com/PrycilaCerqueira/P7_UrbanRead/blob/bd65ed044cc0eef1251684e36f8b9064903371cb/P7_UrbanRead/P7_UrbanRead/FuncHelp.cs#L138-L141

i don't think that's intended - fix needed

**Comment by PrycilaCerqueira** [comment]
It is intended as Google Book can return more than one genre type for the same book—examples: romance, soapy, and fiction.
