### ISSUE TITLE
ISBN ID System.NullReferenceException Error

### ISSUE THREAD

**Issue by PrycilaCerqueira** [PrycilaCerqueira/P7_UrbanRead#7]
I don't see why the code throws me the Null error if neither of the Type or Identifier fields is empty nor null. Please take a look at the image below.
![image](https://github.com/PrycilaCerqueira/P7_UrbanRead/assets/75625742/5cef66e8-5b97-4f0a-8187-c77c905d0683)

**Comment by f-rakete** [comment]
good idea to include filenames and line numbers in your issue 

the issue might arise because you have one case where you set it to null 🙃 
![image](https://github.com/PrycilaCerqueira/P7_UrbanRead/assets/69428398/3797cc1c-e146-4562-855d-abb6a7171cbd)

**Comment by PrycilaCerqueira** [comment]
@f-rakete Thank you! It worked.
